### PR TITLE
The rest of the endpoints

### PR DESCRIPTION
**Pull request by accua**
This PR sets up the rest of the endpoints.

Things to note:
- BlockgroupsEl, and Neighborhoods both don't exist as tables yet and,
- Zoning looked strange once setup at `/zoning`

### CODE REVIEW

**Comment by accua** [comment]
@hassanshamim do you have an idea why this is failing?

**Comment by MikeTheCanuck** [comment]
Embarrassingly I think I have a pretty good idea - looks like I failed in my promise to setup the appropriate env vars in Travis, so the `Test.sh` script didn’t have a value for DOCKER_SERVICE. 

(FYI, in case you hadn’t looked, check the Travis build linked above/below - or [here](https://travis-ci.org/hackoregon/neighborhoods-2018/builds/380716697) - around lines 848-879 of the job log. That output reads to me like the script failed to execute.

I’m in a cab, heading to hotel. I’ll get in and setup the env vars (including the AWS creds that will later be needed in the Travis job to upload the tested container to AWS) once I hit the hotel.

**Comment by MikeTheCanuck** [comment]
Well gents, there's a problem I don't know how to solve: even with all the correct env vars setup in Travis, the `test.sh` script bails with this error:

```
Using existing test database for alias 'default'...
Got an error creating the test database: permission denied to create database
```

Now, the creds we use for each of the databases are privileged for the database associated with the project, but the creds do *not* have permission to create arbitrary databases.  We've run into this with one of the other projects - @nam20485, was that with yours?  I don't recall what the current workaround is for that - we'd discussed a couple of scenarios, but I've lost track of where we landed on that.

**Comment by nam20485** [comment]
> Using existing test database for alias 'default'...
Got an error creating the test database: permission denied to create database

@MikeTheCanuck This is not a problem, it is actually expected with the current code. 

What you are running still has the old unit testing command that requires write access to the DB. @BrianHGrant has found a better solution and created an issue to explain it here: hackoregon/backend-examplar-2018/issues/82

I also have implemented his suggested pattern in hackoregon/disaster-resilience-backend. It seems to work well:

1. It runs the 4 example unit tests I have in my project without requiring any modification to my existing unit tests or structure. (This probably means that we can drop it in to the other existing backend repos and it will automagically work with any unit test cases or structure already present)

2. It **does not require write access**, so it will effectively test the Django app and API endpoints against a DB connection that offers only read-only access. (I have implemented it and tested it on: https://travis-ci.org/hackoregon/disaster-resilience-backend/builds/380495740, where it connects to the new disaster-resilience DB instance you created for me that allows only read-only access) You can see the log of it completing successfully in the travis project)

Given our current lack of a suitable unit testing solution, I think that we should discuss whether we all can agree on going with this solution, or why not, and if so, create a PR against hackoregon/backend-examplar so we can include it.

**Pull request merged**
